languange: node_js
node_js:
- '12'
cache:
  yarn: true
  directories:
  - public
  - ".cache"
script:
- yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github_token:
    secure: THHOT+iU+yFsiWVx6+6c2WwQ8tD7jH4vmO8GR8Zx8aw86IrIeUY4pIqJvq2XV4XS32Udta3mbgyFA29v9Ar7rNExR3Y9Bm27LDIu4Ye+jprHmLHo1aaEflVESdfhDTHwg2FqNAnSF2RCVhA3R8rReSNncq3uQRw8i/k6yilGb1Gxk5rYhiRpaFzhcKd/Zrzdb/caGqzO3tp+U9zc5FYcFBjnmLpIIje0kZgzpqBy4cAKCkFpMqqEn1nzcokRFGvjlqGHQzj+Fbmi8grlxf8yuvfL6kp2/RWsQFRYA3qTmb/u8prPqQAewtcVwH2rQ+ZinNxGJVO3G4DlC4xrbwoJNAL2awKd8CIkSNtklx4I3BWDnkH91HErODWCI0OEuI44v2fUKuYk3hmJ+nUg2AnzwzhP3SKZwcmTssr42ZMQ5gZmbDdBh5pHG8AaPDIGIpuia7aAIVUCjhAl9ighMX8jI9p5Ccc+/Hph2bK0layyvYqIqAycLDRhMNl+Fd+vq3XuAGKegw0Tt0culoWkcOIYzpzAcnRw6J/ZbU+1ToY3pqJVk/nXbI4B2hY9bfN255InEPbDk0l9Ua8bCFrVXPgmxvAm+oTIOSJXojIW1A1Amzb+sh+bwvM6RdseN5d9XcvzxuMftVxsgvupeTR0+i7P3pzRFet2j501vgHRgUhSkcA=
  keep_history: true
  on:
    branch: main
