languange: node_js
node_js:
- '12'

cache:
  directories:
  - node_modules # Cache the node_modules folder for quicker build times
script:
  - npm install
  - npm run build # Runs next build
  - npm run export # Runs next export and generates the out directory
  - touch out/.nojekyll # Creates a file telling Github not to build the project using Jekyll

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  on:
    branch: main
