languange: node_js
node_js:
- '12'
cache:
  yarn: true
  directories:
  - public
  - ".cache"

script:
  - npm run build
  - npm run export
  - touch out/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  on:
    branch: main
